<?php
/**
 * AzureBlobDataReference
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * AzureBlobDataReference Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AzureBlobDataReference implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'base_location' => 'string',
        'connection_string' => 'string',
        'relative_location' => 'string',
        'sas_blob_token' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'base_location' => 'BaseLocation',
        'connection_string' => 'ConnectionString',
        'relative_location' => 'RelativeLocation',
        'sas_blob_token' => 'SasBlobToken'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'base_location' => 'setBaseLocation',
        'connection_string' => 'setConnectionString',
        'relative_location' => 'setRelativeLocation',
        'sas_blob_token' => 'setSasBlobToken'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'base_location' => 'getBaseLocation',
        'connection_string' => 'getConnectionString',
        'relative_location' => 'getRelativeLocation',
        'sas_blob_token' => 'getSasBlobToken'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $base_location 
      * @var string
      */
    protected $base_location;
    
    /**
      * $connection_string 
      * @var string
      */
    protected $connection_string;
    
    /**
      * $relative_location 
      * @var string
      */
    protected $relative_location;
    
    /**
      * $sas_blob_token 
      * @var string
      */
    protected $sas_blob_token;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->base_location = $data["base_location"];
            $this->connection_string = $data["connection_string"];
            $this->relative_location = $data["relative_location"];
            $this->sas_blob_token = $data["sas_blob_token"];
        }
    }
    
    /**
     * Gets base_location
     * @return string
     */
    public function getBaseLocation()
    {
        return $this->base_location;
    }
  
    /**
     * Sets base_location
     * @param string $base_location 
     * @return $this
     */
    public function setBaseLocation($base_location)
    {
        
        $this->base_location = $base_location;
        return $this;
    }
    
    /**
     * Gets connection_string
     * @return string
     */
    public function getConnectionString()
    {
        return $this->connection_string;
    }
  
    /**
     * Sets connection_string
     * @param string $connection_string 
     * @return $this
     */
    public function setConnectionString($connection_string)
    {
        
        $this->connection_string = $connection_string;
        return $this;
    }
    
    /**
     * Gets relative_location
     * @return string
     */
    public function getRelativeLocation()
    {
        return $this->relative_location;
    }
  
    /**
     * Sets relative_location
     * @param string $relative_location 
     * @return $this
     */
    public function setRelativeLocation($relative_location)
    {
        
        $this->relative_location = $relative_location;
        return $this;
    }
    
    /**
     * Gets sas_blob_token
     * @return string
     */
    public function getSasBlobToken()
    {
        return $this->sas_blob_token;
    }
  
    /**
     * Sets sas_blob_token
     * @param string $sas_blob_token 
     * @return $this
     */
    public function setSasBlobToken($sas_blob_token)
    {
        
        $this->sas_blob_token = $sas_blob_token;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
