<?php
/**
 * AzureBlobDataReference
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experiment created on 5/25/2016
 *
 * No description provided for this web service.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AzureBlobDataReference Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AzureBlobDataReference implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AzureBlobDataReference';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'base_location' => 'string',
        'connection_string' => 'string',
        'relative_location' => 'string',
        'sas_blob_token' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'base_location' => 'BaseLocation',
        'connection_string' => 'ConnectionString',
        'relative_location' => 'RelativeLocation',
        'sas_blob_token' => 'SasBlobToken'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'base_location' => 'setBaseLocation',
        'connection_string' => 'setConnectionString',
        'relative_location' => 'setRelativeLocation',
        'sas_blob_token' => 'setSasBlobToken'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'base_location' => 'getBaseLocation',
        'connection_string' => 'getConnectionString',
        'relative_location' => 'getRelativeLocation',
        'sas_blob_token' => 'getSasBlobToken'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['base_location'] = isset($data['base_location']) ? $data['base_location'] : null;
        $this->container['connection_string'] = isset($data['connection_string']) ? $data['connection_string'] : null;
        $this->container['relative_location'] = isset($data['relative_location']) ? $data['relative_location'] : null;
        $this->container['sas_blob_token'] = isset($data['sas_blob_token']) ? $data['sas_blob_token'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets base_location
     * @return string
     */
    public function getBaseLocation()
    {
        return $this->container['base_location'];
    }

    /**
     * Sets base_location
     * @param string $base_location
     * @return $this
     */
    public function setBaseLocation($base_location)
    {
        $this->container['base_location'] = $base_location;

        return $this;
    }

    /**
     * Gets connection_string
     * @return string
     */
    public function getConnectionString()
    {
        return $this->container['connection_string'];
    }

    /**
     * Sets connection_string
     * @param string $connection_string
     * @return $this
     */
    public function setConnectionString($connection_string)
    {
        $this->container['connection_string'] = $connection_string;

        return $this;
    }

    /**
     * Gets relative_location
     * @return string
     */
    public function getRelativeLocation()
    {
        return $this->container['relative_location'];
    }

    /**
     * Sets relative_location
     * @param string $relative_location
     * @return $this
     */
    public function setRelativeLocation($relative_location)
    {
        $this->container['relative_location'] = $relative_location;

        return $this;
    }

    /**
     * Gets sas_blob_token
     * @return string
     */
    public function getSasBlobToken()
    {
        return $this->container['sas_blob_token'];
    }

    /**
     * Sets sas_blob_token
     * @param string $sas_blob_token
     * @return $this
     */
    public function setSasBlobToken($sas_blob_token)
    {
        $this->container['sas_blob_token'] = $sas_blob_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
