<?php
/**
 * BatchExecutionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * BatchExecutionRequest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchExecutionRequest implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'global_parameters' => '\Swagger\Client\Model\GlobalParameters',
        'inputs' => '\Swagger\Client\Model\BatchInputs',
        'outputs' => '\Swagger\Client\Model\BatchOutputs'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'global_parameters' => 'GlobalParameters',
        'inputs' => 'Inputs',
        'outputs' => 'Outputs'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'global_parameters' => 'setGlobalParameters',
        'inputs' => 'setInputs',
        'outputs' => 'setOutputs'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'global_parameters' => 'getGlobalParameters',
        'inputs' => 'getInputs',
        'outputs' => 'getOutputs'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $global_parameters 
      * @var \Swagger\Client\Model\GlobalParameters
      */
    protected $global_parameters;
    
    /**
      * $inputs 
      * @var \Swagger\Client\Model\BatchInputs
      */
    protected $inputs;
    
    /**
      * $outputs 
      * @var \Swagger\Client\Model\BatchOutputs
      */
    protected $outputs;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->global_parameters = $data["global_parameters"];
            $this->inputs = $data["inputs"];
            $this->outputs = $data["outputs"];
        }
    }
    
    /**
     * Gets global_parameters
     * @return \Swagger\Client\Model\GlobalParameters
     */
    public function getGlobalParameters()
    {
        return $this->global_parameters;
    }
  
    /**
     * Sets global_parameters
     * @param \Swagger\Client\Model\GlobalParameters $global_parameters 
     * @return $this
     */
    public function setGlobalParameters($global_parameters)
    {
        
        $this->global_parameters = $global_parameters;
        return $this;
    }
    
    /**
     * Gets inputs
     * @return \Swagger\Client\Model\BatchInputs
     */
    public function getInputs()
    {
        return $this->inputs;
    }
  
    /**
     * Sets inputs
     * @param \Swagger\Client\Model\BatchInputs $inputs 
     * @return $this
     */
    public function setInputs($inputs)
    {
        
        $this->inputs = $inputs;
        return $this;
    }
    
    /**
     * Gets outputs
     * @return \Swagger\Client\Model\BatchOutputs
     */
    public function getOutputs()
    {
        return $this->outputs;
    }
  
    /**
     * Sets outputs
     * @param \Swagger\Client\Model\BatchOutputs $outputs 
     * @return $this
     */
    public function setOutputs($outputs)
    {
        
        $this->outputs = $outputs;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
