<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 * DO NOT DIRECTLY USE THIS FILE
 * USE Matches.php
 * TO MAKE YOUR CHANGES AND DATABASE ACCESS
*/

namespace App\Http\DataAccess\Models;

use Luticate\Utils\LuModel;
use App\Http\DBO\MatchesDbo;

class MatchesModel extends LuModel
{
    function __construct()
    {
        parent::__construct();
        $this->timestamps = false;
    }

    public function toDbo()
    {
        $dbo = new MatchesDbo();

        $dbo->setId($this->id);
        $dbo->setPlayer1Id($this->player1_id);
        $dbo->setPlayer2Id($this->player2_id);
        $dbo->setSet1Id($this->set1_id);
        $dbo->setSet2Id($this->set2_id);
        $dbo->setSet3Id($this->set3_id);
        $dbo->setSet4Id($this->set4_id);
        $dbo->setSet5Id($this->set5_id);
        $dbo->setDate($this->date);
        $dbo->setTournamentId($this->tournament_id);

        return $dbo;
    }

    /**
     * @param $dbo MatchesDbo
     * @param $model LuModel|null
     * @return Matches
     */
    public function fromDbo($dbo, $model = null)
    {
        if (is_null($model))
            $model = new Matches();

        $model->id = $dbo->getId();
        $model->player1_id = $dbo->getPlayer1Id();
        $model->player2_id = $dbo->getPlayer2Id();
        $model->set1_id = $dbo->getSet1Id();
        $model->set2_id = $dbo->getSet2Id();
        $model->set3_id = $dbo->getSet3Id();
        $model->set4_id = $dbo->getSet4Id();
        $model->set5_id = $dbo->getSet5Id();
        $model->date = $dbo->getDate();
        $model->tournament_id = $dbo->getTournamentId();

        return $model;
    }
}