<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 * DO NOT DIRECTLY USE THIS FILE
 * USE Players.php
 * TO MAKE YOUR CHANGES AND DATABASE ACCESS
*/

namespace App\Http\DataAccess\Models;

use Luticate\Utils\LuModel;
use App\Http\DBO\PlayersDbo;

class PlayersModel extends LuModel
{
    function __construct()
    {
        parent::__construct();
        $this->timestamps = false;
    }

    public function toDbo()
    {
        $dbo = new PlayersDbo();

        $dbo->setId($this->id);
        $dbo->setName($this->name);
        $dbo->setBirthdate($this->birthdate);
        $dbo->setSex($this->sex);
        $dbo->setCountry($this->country);
        $dbo->setWeight($this->weight);
        $dbo->setSize($this->size);
        $dbo->setPictureUrl($this->picture_url);

        return $dbo;
    }

    /**
     * @param $dbo PlayersDbo
     * @param $model LuModel|null
     * @return Players
     */
    public function fromDbo($dbo, $model = null)
    {
        if (is_null($model))
            $model = new Players();

        $model->id = $dbo->getId();
        $model->name = $dbo->getName();
        $model->birthdate = $dbo->getBirthdate();
        $model->sex = $dbo->getSex();
        $model->country = $dbo->getCountry();
        $model->weight = $dbo->getWeight();
        $model->size = $dbo->getSize();
        $model->picture_url = $dbo->getPictureUrl();

        return $model;
    }
}