<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 * DO NOT DIRECTLY USE THIS FILE
 * USE Rankings.php
 * TO MAKE YOUR CHANGES AND DATABASE ACCESS
*/

namespace App\Http\DataAccess\Models;

use Luticate\Utils\LuModel;
use App\Http\DBO\RankingsDbo;

class RankingsModel extends LuModel
{
    function __construct()
    {
        parent::__construct();
        $this->timestamps = false;
    }

    public function toDbo()
    {
        $dbo = new RankingsDbo();

        $dbo->setPlayerId($this->player_id);
        $dbo->setRank($this->rank);
        $dbo->setYear($this->year);

        return $dbo;
    }

    /**
     * @param $dbo RankingsDbo
     * @param $model LuModel|null
     * @return Rankings
     */
    public function fromDbo($dbo, $model = null)
    {
        if (is_null($model))
            $model = new Rankings();

        $model->player_id = $dbo->getPlayerId();
        $model->rank = $dbo->getRank();
        $model->year = $dbo->getYear();

        return $model;
    }
}