<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 * DO NOT DIRECTLY USE THIS FILE
 * USE Sets.php
 * TO MAKE YOUR CHANGES AND DATABASE ACCESS
*/

namespace App\Http\DataAccess\Models;

use Luticate\Utils\LuModel;
use App\Http\DBO\SetsDbo;

class SetsModel extends LuModel
{
    function __construct()
    {
        parent::__construct();
        $this->timestamps = false;
    }

    public function toDbo()
    {
        $dbo = new SetsDbo();

        $dbo->setId($this->id);
        $dbo->setPlayer1Score($this->player1_score);
        $dbo->setPlayer2Score($this->player2_score);
        $dbo->setPlayer1TieBreak($this->player1_tie_break);
        $dbo->setPlayer2TieBreak($this->player2_tie_break);

        return $dbo;
    }

    /**
     * @param $dbo SetsDbo
     * @param $model LuModel|null
     * @return Sets
     */
    public function fromDbo($dbo, $model = null)
    {
        if (is_null($model))
            $model = new Sets();

        $model->id = $dbo->getId();
        $model->player1_score = $dbo->getPlayer1Score();
        $model->player2_score = $dbo->getPlayer2Score();
        $model->player1_tie_break = $dbo->getPlayer1TieBreak();
        $model->player2_tie_break = $dbo->getPlayer2TieBreak();

        return $model;
    }
}