<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 * DO NOT DIRECTLY USE THIS FILE
 * USE Tournaments.php
 * TO MAKE YOUR CHANGES AND DATABASE ACCESS
*/

namespace App\Http\DataAccess\Models;

use Luticate\Utils\LuModel;
use App\Http\DBO\TournamentsDbo;

class TournamentsModel extends LuModel
{
    function __construct()
    {
        parent::__construct();
        $this->timestamps = false;
    }

    public function toDbo()
    {
        $dbo = new TournamentsDbo();

        $dbo->setId($this->id);
        $dbo->setName($this->name);
        $dbo->setGroundType($this->ground_type);
        $dbo->setYear($this->year);

        return $dbo;
    }

    /**
     * @param $dbo TournamentsDbo
     * @param $model LuModel|null
     * @return Tournaments
     */
    public function fromDbo($dbo, $model = null)
    {
        if (is_null($model))
            $model = new Tournaments();

        $model->id = $dbo->getId();
        $model->name = $dbo->getName();
        $model->ground_type = $dbo->getGroundType();
        $model->year = $dbo->getYear();

        return $model;
    }
}