<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class GroundTypesDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "Id" => $this->_id,
            "Name" => $this->_name
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new GroundTypesDbo();
        if (isset($json["Id"])) {
            $dbo->setId($json["Id"]);
        }
        if (isset($json["Name"])) {
            $dbo->setName($json["Name"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new GroundTypesDbo();
        $dbo->setId(42);
        $dbo->setName("sample string");
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_id;
    public function getId()
    {
        return $this->_id;
    }
    public function setId($value)
    {
        $this->_id = $value;
    }

    /**
     * @var string
     */
    protected $_name;
    public function getName()
    {
        return $this->_name;
    }
    public function setName($value)
    {
        $this->_name = $value;
    }
}
