<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class MatchesDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "Id" => $this->_id,
            "Player1Id" => $this->_player1Id,
            "Player2Id" => $this->_player2Id,
            "Set1Id" => $this->_set1Id,
            "Set2Id" => $this->_set2Id,
            "Set3Id" => $this->_set3Id,
            "Set4Id" => $this->_set4Id,
            "Set5Id" => $this->_set5Id,
            "Date" => $this->_date,
            "TournamentId" => $this->_tournamentId
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new MatchesDbo();
        if (isset($json["Id"])) {
            $dbo->setId($json["Id"]);
        }
        if (isset($json["Player1Id"])) {
            $dbo->setPlayer1Id($json["Player1Id"]);
        }
        if (isset($json["Player2Id"])) {
            $dbo->setPlayer2Id($json["Player2Id"]);
        }
        if (isset($json["Set1Id"])) {
            $dbo->setSet1Id($json["Set1Id"]);
        }
        if (isset($json["Set2Id"])) {
            $dbo->setSet2Id($json["Set2Id"]);
        }
        if (isset($json["Set3Id"])) {
            $dbo->setSet3Id($json["Set3Id"]);
        }
        if (isset($json["Set4Id"])) {
            $dbo->setSet4Id($json["Set4Id"]);
        }
        if (isset($json["Set5Id"])) {
            $dbo->setSet5Id($json["Set5Id"]);
        }
        if (isset($json["Date"])) {
            $dbo->setDate($json["Date"]);
        }
        if (isset($json["TournamentId"])) {
            $dbo->setTournamentId($json["TournamentId"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new MatchesDbo();
        $dbo->setId(42);
        $dbo->setPlayer1Id(42);
        $dbo->setPlayer2Id(42);
        $dbo->setSet1Id(42);
        $dbo->setSet2Id(42);
        $dbo->setSet3Id(42);
        $dbo->setSet4Id(42);
        $dbo->setSet5Id(42);
        $dbo->setDate("sample string");
        $dbo->setTournamentId(42);
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_id;
    public function getId()
    {
        return $this->_id;
    }
    public function setId($value)
    {
        $this->_id = $value;
    }

    /**
     * @var integer
     */
    protected $_player1Id;
    public function getPlayer1Id()
    {
        return $this->_player1Id;
    }
    public function setPlayer1Id($value)
    {
        $this->_player1Id = $value;
    }

    /**
     * @var integer
     */
    protected $_player2Id;
    public function getPlayer2Id()
    {
        return $this->_player2Id;
    }
    public function setPlayer2Id($value)
    {
        $this->_player2Id = $value;
    }

    /**
     * @var integer
     */
    protected $_set1Id;
    public function getSet1Id()
    {
        return $this->_set1Id;
    }
    public function setSet1Id($value)
    {
        $this->_set1Id = $value;
    }

    /**
     * @var integer
     */
    protected $_set2Id;
    public function getSet2Id()
    {
        return $this->_set2Id;
    }
    public function setSet2Id($value)
    {
        $this->_set2Id = $value;
    }

    /**
     * @var integer
     */
    protected $_set3Id;
    public function getSet3Id()
    {
        return $this->_set3Id;
    }
    public function setSet3Id($value)
    {
        $this->_set3Id = $value;
    }

    /**
     * @var integer
     */
    protected $_set4Id;
    public function getSet4Id()
    {
        return $this->_set4Id;
    }
    public function setSet4Id($value)
    {
        $this->_set4Id = $value;
    }

    /**
     * @var integer
     */
    protected $_set5Id;
    public function getSet5Id()
    {
        return $this->_set5Id;
    }
    public function setSet5Id($value)
    {
        $this->_set5Id = $value;
    }

    /**
     * @var timestamp without time zone
     */
    protected $_date;
    public function getDate()
    {
        return $this->_date;
    }
    public function setDate($value)
    {
        $this->_date = $value;
    }

    /**
     * @var integer
     */
    protected $_tournamentId;
    public function getTournamentId()
    {
        return $this->_tournamentId;
    }
    public function setTournamentId($value)
    {
        $this->_tournamentId = $value;
    }
}
