<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class RankingsDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "PlayerId" => $this->_playerId,
            "Rank" => $this->_rank,
            "Year" => $this->_year
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new RankingsDbo();
        if (isset($json["PlayerId"])) {
            $dbo->setPlayerId($json["PlayerId"]);
        }
        if (isset($json["Rank"])) {
            $dbo->setRank($json["Rank"]);
        }
        if (isset($json["Year"])) {
            $dbo->setYear($json["Year"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new RankingsDbo();
        $dbo->setPlayerId(42);
        $dbo->setRank(42);
        $dbo->setYear(42);
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_playerId;
    public function getPlayerId()
    {
        return $this->_playerId;
    }
    public function setPlayerId($value)
    {
        $this->_playerId = $value;
    }

    /**
     * @var integer
     */
    protected $_rank;
    public function getRank()
    {
        return $this->_rank;
    }
    public function setRank($value)
    {
        $this->_rank = $value;
    }

    /**
     * @var integer
     */
    protected $_year;
    public function getYear()
    {
        return $this->_year;
    }
    public function setYear($value)
    {
        $this->_year = $value;
    }
}
