<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class SetsDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "Id" => $this->_id,
            "Player1Score" => $this->_player1Score,
            "Player2Score" => $this->_player2Score,
            "Player1TieBreak" => $this->_player1TieBreak,
            "Player2TieBreak" => $this->_player2TieBreak
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new SetsDbo();
        if (isset($json["Id"])) {
            $dbo->setId($json["Id"]);
        }
        if (isset($json["Player1Score"])) {
            $dbo->setPlayer1Score($json["Player1Score"]);
        }
        if (isset($json["Player2Score"])) {
            $dbo->setPlayer2Score($json["Player2Score"]);
        }
        if (isset($json["Player1TieBreak"])) {
            $dbo->setPlayer1TieBreak($json["Player1TieBreak"]);
        }
        if (isset($json["Player2TieBreak"])) {
            $dbo->setPlayer2TieBreak($json["Player2TieBreak"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new SetsDbo();
        $dbo->setId(42);
        $dbo->setPlayer1Score(42);
        $dbo->setPlayer2Score(42);
        $dbo->setPlayer1TieBreak(42);
        $dbo->setPlayer2TieBreak(42);
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_id;
    public function getId()
    {
        return $this->_id;
    }
    public function setId($value)
    {
        $this->_id = $value;
    }

    /**
     * @var integer
     */
    protected $_player1Score;
    public function getPlayer1Score()
    {
        return $this->_player1Score;
    }
    public function setPlayer1Score($value)
    {
        $this->_player1Score = $value;
    }

    /**
     * @var integer
     */
    protected $_player2Score;
    public function getPlayer2Score()
    {
        return $this->_player2Score;
    }
    public function setPlayer2Score($value)
    {
        $this->_player2Score = $value;
    }

    /**
     * @var integer
     */
    protected $_player1TieBreak;
    public function getPlayer1TieBreak()
    {
        return $this->_player1TieBreak;
    }
    public function setPlayer1TieBreak($value)
    {
        $this->_player1TieBreak = $value;
    }

    /**
     * @var integer
     */
    protected $_player2TieBreak;
    public function getPlayer2TieBreak()
    {
        return $this->_player2TieBreak;
    }
    public function setPlayer2TieBreak($value)
    {
        $this->_player2TieBreak = $value;
    }
}
