<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class TournamentsDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "Id" => $this->_id,
            "Name" => $this->_name,
            "GroundType" => $this->_groundType,
            "Year" => $this->_year
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new TournamentsDbo();
        if (isset($json["Id"])) {
            $dbo->setId($json["Id"]);
        }
        if (isset($json["Name"])) {
            $dbo->setName($json["Name"]);
        }
        if (isset($json["GroundType"])) {
            $dbo->setGroundType($json["GroundType"]);
        }
        if (isset($json["Year"])) {
            $dbo->setYear($json["Year"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new TournamentsDbo();
        $dbo->setId(42);
        $dbo->setName("sample string");
        $dbo->setGroundType(42);
        $dbo->setYear(42);
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_id;
    public function getId()
    {
        return $this->_id;
    }
    public function setId($value)
    {
        $this->_id = $value;
    }

    /**
     * @var string
     */
    protected $_name;
    public function getName()
    {
        return $this->_name;
    }
    public function setName($value)
    {
        $this->_name = $value;
    }

    /**
     * @var integer
     */
    protected $_groundType;
    public function getGroundType()
    {
        return $this->_groundType;
    }
    public function setGroundType($value)
    {
        $this->_groundType = $value;
    }

    /**
     * @var integer
     */
    protected $_year;
    public function getYear()
    {
        return $this->_year;
    }
    public function setYear($value)
    {
        $this->_year = $value;
    }
}
