<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpDbo;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerWinNumberLastMonth extends LuSpDbo {

    /**
    * @param $dam
    * @return \App\Http\DataAccess\SP\SpGetPlayerWinNumberLastMonth|null
    */
    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerWinNumberLastMonth();

        $dbo->setSpGetPlayerWinNumberLastMonth(LuStringUtils::convertJsonString($dam->sp_get_player_win_number_last_month));

        return $dbo;
    }


    /**
    * @param $in_id integer
    * @param $in_date timestamp without time zone
    * @return \App\Http\DataAccess\SP\SpGetPlayerWinNumberLastMonth;
    */
    public static function execute($in_id, $in_date)
    {
        $values = DB::select('SELECT to_json(data.sp_get_player_win_number_last_month) AS sp_get_player_win_number_last_month FROM sp_get_player_win_number_last_month(:in_id, :in_date) data', array(":in_id" => $in_id, ":in_date" => $in_date));
        return self::damToDbo($values[0]);
    }


    public function jsonSerialize()
    {
        return array(
            "SpGetPlayerWinNumberLastMonth" => $this->_spGetPlayerWinNumberLastMonth
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new SpGetPlayerWinNumberLastMonth();
        if (isset($json["SpGetPlayerWinNumberLastMonth"])) {
            $dbo->setSpGetPlayerWinNumberLastMonth($json["SpGetPlayerWinNumberLastMonth"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new SpGetPlayerWinNumberLastMonth();
        $dbo->setSpGetPlayerWinNumberLastMonth(42);
        return $dbo;
    }


    /**
    * @var integer
    */
    protected $_spGetPlayerWinNumberLastMonth;
    public function getSpGetPlayerWinNumberLastMonth()
    {
        return $this->_spGetPlayerWinNumberLastMonth;
    }
    public function setSpGetPlayerWinNumberLastMonth($value)
    {
        $this->_spGetPlayerWinNumberLastMonth = $value;
    }
}
