<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpDbo;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerAge extends LuSpDbo {

    /**
    * @param $dam
    * @return \App\Http\DataAccess\SP\SpGetPlayerAge|null
    */
    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerAge();

        $dbo->setAge(LuStringUtils::convertJsonString($dam->age));

        return $dbo;
    }


    /**
    * @param $in_id integer
    * @return \App\Http\DataAccess\SP\SpGetPlayerAge;
    */
    public static function execute($in_id)
    {
        $values = DB::select('SELECT to_json(data.age) AS age FROM sp_get_player_age(:in_id) data', array(":in_id" => $in_id));
        return self::damToDbo($values[0]);
    }


    public function jsonSerialize()
    {
        return array(
            "Age" => $this->_age
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new SpGetPlayerAge();
        if (isset($json["Age"])) {
            $dbo->setAge($json["Age"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new SpGetPlayerAge();
        $dbo->setAge(42);
        return $dbo;
    }


    /**
    * @var integer
    */
    protected $_age;
    public function getAge()
    {
        return $this->_age;
    }
    public function setAge($value)
    {
        $this->_age = $value;
    }
}
