<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpModel;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetMatchWinner extends LuSpModel {

    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetMatchWinner();

        $dbo->setNumber($dam->number);

        return $dbo;
    }


    public static function execute($match_id)
    {
        $values = DB::select('SELECT * FROM sp_get_match_winner(:match_id)', array(":match_id" => $match_id));
        return self::damToDbo($values[0]);
    }



    /**
    * @var integer
    */
    protected $_number;
    public function getNumber()
    {
        return $this->_number;
    }
    public function setNumber($value)
    {
        $this->_number = $value;
    }
}
