<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpDbo;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerFull extends LuSpDbo {

    /**
    * @param $dam
    * @return \App\Http\DataAccess\SP\SpGetPlayerFull|null
    */
    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerFull();

        $dbo->setPlayer(LuStringUtils::convertJsonString($dam->player));
        $dbo->setMatchWinCount(LuStringUtils::convertJsonString($dam->match_win_count));

        return $dbo;
    }


    /**
    * @param $player_id integer
    * @return \App\Http\DataAccess\SP\SpGetPlayerFull;
    */
    public static function execute($player_id)
    {
        $values = DB::select('SELECT to_json(data.player) AS player, to_json(data.match_win_count) AS match_win_count FROM sp_get_player_full(:player_id) data', array(":player_id" => $player_id));
        return self::damToDbo($values[0]);
    }


    public function jsonSerialize()
    {
        return array(
            "Player" => $this->_player,
            "MatchWinCount" => $this->_matchWinCount
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new SpGetPlayerFull();
        if (isset($json["Player"])) {
            $dbo->setPlayer($json["Player"]);
        }
        if (isset($json["MatchWinCount"])) {
            $dbo->setMatchWinCount($json["MatchWinCount"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new SpGetPlayerFull();
        $dbo->setPlayer("sample string");
        $dbo->setMatchWinCount(42);
        return $dbo;
    }


    /**
    * @var USER-DEFINED
    */
    protected $_player;
    public function getPlayer()
    {
        return $this->_player;
    }
    public function setPlayer($value)
    {
        $this->_player = $value;
    }

    /**
    * @var integer
    */
    protected $_matchWinCount;
    public function getMatchWinCount()
    {
        return $this->_matchWinCount;
    }
    public function setMatchWinCount($value)
    {
        $this->_matchWinCount = $value;
    }
}
