<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpModel;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerBestGround extends LuSpModel {

    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerBestGround();

        $dbo->setGroundType($dam->ground_type);

        return $dbo;
    }


    public static function execute($player_id)
    {
        $values = DB::select('SELECT * FROM sp_get_player_best_ground(:player_id)', array(":player_id" => $player_id));
        return self::damToDbo($values[0]);
    }



    /**
    * @var integer
    */
    protected $_groundType;
    public function getGroundType()
    {
        return $this->_groundType;
    }
    public function setGroundType($value)
    {
        $this->_groundType = $value;
    }
}
