<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpModel;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerWinPercent extends LuSpModel {

    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerWinPercent();

        $dbo->setPercent($dam->percent);

        return $dbo;
    }


    public static function execute($player_id, $year)
    {
        $values = DB::select('SELECT * FROM sp_get_player_win_percent(:player_id, :year)', array(":player_id" => $player_id, ":year" => $year));
        return self::damToDbo($values[0]);
    }



    /**
    * @var double
    */
    protected $_percent;
    public function getPercent()
    {
        return $this->_percent;
    }
    public function setPercent($value)
    {
        $this->_percent = $value;
    }
}
