<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpDbo;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpGetPlayerWinThreeMonth extends LuSpDbo {

    /**
    * @param $dam
    * @return \App\Http\DataAccess\SP\SpGetPlayerWinThreeMonth|null
    */
    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpGetPlayerWinThreeMonth();

        $dbo->setNb(LuStringUtils::convertJsonString($dam->nb));
        $dbo->setTotal(LuStringUtils::convertJsonString($dam->total));
        $dbo->setResult(LuStringUtils::convertJsonString($dam->result));

        return $dbo;
    }


    /**
    * @param $in_id integer
    * @param $in_date timestamp without time zone
    * @return \App\Http\DataAccess\SP\SpGetPlayerWinThreeMonth;
    */
    public static function execute($in_id, $in_date)
    {
        $values = DB::select('SELECT to_json(data.nb) AS nb, to_json(data.total) AS total, to_json(data.result) AS result FROM sp_get_player_win_three_month(:in_id, :in_date) data', array(":in_id" => $in_id, ":in_date" => $in_date));
        return self::damToDbo($values[0]);
    }


    public function jsonSerialize()
    {
        return array(
            "Nb" => $this->_nb,
            "Total" => $this->_total,
            "Result" => $this->_result
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new SpGetPlayerWinThreeMonth();
        if (isset($json["Nb"])) {
            $dbo->setNb($json["Nb"]);
        }
        if (isset($json["Total"])) {
            $dbo->setTotal($json["Total"]);
        }
        if (isset($json["Result"])) {
            $dbo->setResult($json["Result"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new SpGetPlayerWinThreeMonth();
        $dbo->setNb(42);
        $dbo->setTotal(42);
        $dbo->setResult(42);
        return $dbo;
    }


    /**
    * @var integer
    */
    protected $_nb;
    public function getNb()
    {
        return $this->_nb;
    }
    public function setNb($value)
    {
        $this->_nb = $value;
    }

    /**
    * @var integer
    */
    protected $_total;
    public function getTotal()
    {
        return $this->_total;
    }
    public function setTotal($value)
    {
        $this->_total = $value;
    }

    /**
    * @var integer
    */
    protected $_result;
    public function getResult()
    {
        return $this->_result;
    }
    public function setResult($value)
    {
        $this->_result = $value;
    }
}
