<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpModel;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpMayInsertTournament extends LuSpModel {

    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpMayInsertTournament();

        $dbo->setTournamentId($dam->tournament_id);

        return $dbo;
    }


    public static function execute($tournament_name, $tournament_ground, $tournament_year)
    {
        $values = DB::select('SELECT * FROM sp_may_insert_tournament(:tournament_name, :tournament_ground, :tournament_year)', array(":tournament_name" => $tournament_name, ":tournament_ground" => $tournament_ground, ":tournament_year" => $tournament_year));
        return self::damToDbo($values[0]);
    }



    /**
    * @var integer
    */
    protected $_tournamentId;
    public function getTournamentId()
    {
        return $this->_tournamentId;
    }
    public function setTournamentId($value)
    {
        $this->_tournamentId = $value;
    }
}
