<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DataAccess\SP;

use Luticate\Utils\LuSpModel;
use Luticate\Utils\LuMultipleDbo;
use Luticate\Utils\LuStringUtils;
use Illuminate\Support\Facades\DB;

class SpMayInsertGround extends LuSpModel {

    protected static function damToDbo($dam)
    {
        if (is_null($dam))
            return null;
        $dbo = new SpMayInsertGround();

        $dbo->setGroundId($dam->ground_id);

        return $dbo;
    }


    public static function execute($ground_name)
    {
        $values = DB::select('SELECT * FROM sp_may_insert_ground(:ground_name)', array(":ground_name" => $ground_name));
        return self::damToDbo($values[0]);
    }



    /**
    * @var integer
    */
    protected $_groundId;
    public function getGroundId()
    {
        return $this->_groundId;
    }
    public function setGroundId($value)
    {
        $this->_groundId = $value;
    }
}
